
CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` bigint NOT NULL,
  `AGE` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `lOCATION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE TABLE `PRODUCT` (
  `PRODUCT_CODE` varchar(255) NOT NULL,
  `COST` decimal(19,2) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_CODE`)
) ;

CREATE TABLE `PURCHASE_ORDER` (
  `PURCHASE_ORDER_ID` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CUSTOMER_ID` bigint DEFAULT NULL,
  `PRODUCT_CODE` varchar(255) DEFAULT NULL,
  `QUANTITY` int DEFAULT NULL,
  `PURCHASE_ORDER_TIME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PURCHASE_ORDER_ID`)
);
